# u can run docker compose to build and start the services defined in this file via this command: `docker-compose up --build`
services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: services/catalog/Catalog.API/Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - CatalogDb
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://CatalogDb:27017
      - DatabaseSettings__DatabaseName=CatalogDb
      - DatabaseSettings__ProductBrandsCollectionName=Brands
      - DatabaseSettings__ProductTypesCollectionName=Types
      - DatabaseSettings__ProductsCollectionName=Products
  CatalogDb:
    image: mongo
    container_name: CatalogDb
    ports:
      - "27017:27017"
    volumes:
      - catalogdata:/data/db
volumes:
  catalogdata:
